### ISSUE TITLE
Inference allow for retries

### ISSUE THREAD

**Issue by etredal** [Azure/kaito#291]
[models/llama2/inference-api.py](https://github.com/ishaansehgal99/kaito/tree/e0f3a352799ec55379e5307b2a8bdbecfad99650/presets/models/llama2/inference-api.py)

The worker task could be more flexible by allowing for retries when a socket timeout has occurred.  We would need to have maximum number of retries as well to prevent it from getting into a continuous loop of timeouts.

**Original**
except Exception as e:  
            print(f"Error in Worker Listen Task", e)  
            if 'Socket Timeout' in str(e):  
                print("A socket timeout occurred.")  
            os.killpg(os.getpgrp(), signal.SIGTERM)
            
**Proposed**
def worker_listen_tasks():  
    max_socket_timeouts = 3  
    socket_timeout_count = 0  
    ...  
    if 'Socket Timeout' in str(e):  
                socket_timeout_count += 1  
                if socket_timeout_count > max_socket_timeouts:  
                    print("Maximum socket timeouts exceeded. Exiting...")  
                    os.killpg(os.getpgrp(), signal.SIGTERM)  
                else:  
                    print(f"Retrying operation after socket timeout (attempt {socket_timeout_count}/{max_socket_timeouts})...")  
                    continue  # Continue the loop to retry

@Fei-Guo  @ishaansehgal99

**Comment by ishaansehgal99** [comment]
Hey @etredal thanks for the point! :) This is something we've looked at, we have a parameter called `max_restarts` in our torch rdzv params. This will restart the worker or master in the event of any of failures. By default this is set to three.
