### ISSUE TITLE
failed calling webhook when namespace is not `kaito-workspace`

### ISSUE THREAD

**Issue by philwelz** [Azure/kaito#336]
**Describe the bug**

If you follow the installation docs [here](https://github.com/Azure/kaito/blob/main/docs/installation.md) and [here](https://github.com/Azure/kaito/tree/main/charts/kaito/workspace) it is stated to install the workspace controller to the namespace `kaito-workspace`. But when you do this, you get an validation error when adding any preset model.

**Steps To Reproduce**

```
helm repo add kaito https://azure.github.io/kaito/charts/kaito
helm repo update
helm install workspace kaito/workspace --namespace kaito-workspace --create-namespace
kubectl apply -f https://raw.githubusercontent.com/Azure/kaito/main/examples/inference/kaito_workspace_phi-2.yaml
```

**Expected behavior**

Installation in any namespace should be to final solution, but until that the docs should be adopted.

**Logs**

`Error from server (InternalError): error when creating "https://raw.githubusercontent.com/Azure/kaito/main/examples/inference/kaito_workspace_phi-2.yaml": Internal error occurred: failed calling webhook "validation.workspace.kaito.sh": failed to call webhook: Post "https://workspace.workspace.svc:9443/?timeout=10s": service "workspace" not found`

**Environment**

- Kubernetes version (use `kubectl version`): v1.28.5

**Additional context**

PR for this is created here #334

**Comment by ishaansehgal99** [comment]
Thanks for pointing out this issue with the namespace reference in our Helm chart. We've identified the problem and are addressing it in Pull Request [#337](https://github.com/Azure/kaito/pull/337), which will be included in our next release. Until then, please install the workspace controller in the default namespace as a temporary workaround. Apologies for the inconvenience and appreciate your patience.
