### ISSUE TITLE
Phi-3 reject by validation.workspace.kaito.sh

### ISSUE THREAD

**Issue by philwelz** [Azure/kaito#481]
**Describe the bug**

When trying to apply the Phi-3 example the Kaito validation service rejects the Phi-3 LLM.

**Steps To Reproduce**

`kubectl apply -f https://raw.githubusercontent.com/Azure/kaito/main/examples/inference/kaito_workspace_phi_3.yaml`

**Expected behavior**

Workspace is created.

**Logs**

```
Error from server (InternalError): error when creating "https://raw.githubusercontent.com/Azure/kaito/main/examples/inference/kaito_workspace_phi_3.yaml": Internal error occurred: failed calling webhook "validation.workspace.kaito.sh": failed to call webhook: Post "https://workspace.workspace.svc:9443/validate/workspace.kaito.sh?timeout=10s": EOF
```

**Environment**

- Kubernetes version (use `kubectl version`): v1.28.9
- Install tools: workspace-0.2.2, gpu-provisioner-0.2.0

**Comment by ishaansehgal99** [comment]
Hey @philwelz are you building Kaito from source (upstream)? Or using a release version? We have not included phi-3 in a release yet so this error is expected.

**Comment by ishaansehgal99** [comment]
Closing issue as this error is expected for now.

**Comment by rliberoff** [comment]
Hi!

Do you know when we could get PIH-3 working with Kaito?

Thank you!

**Comment by rliberoff** [comment]
Hi again,

Actually, the question would be if release `v0.3.0 - 2024-07-12` is already available in Azure to use with AKS?

Is it available in all regions?

Is there something I should do to update the feature?

Thank you!
