### ISSUE TITLE
Add the ability to edit existing workspace with kubectl edit command

### ISSUE THREAD

**Issue by pauldotyu** [Azure/kaito#557]
**Is your feature request related to a problem? Please describe.**

When deploying an inferencing workspace with fine-tuned adapters, I'd like the ability to edit the `workspace.inference.adapters.source.image` property using a `kubectl edit workspace` command so that I can easily swap out adapters without having to recreate the entire workspace which can delete and re-provision a new GPU node.

**Describe the solution you'd like**

Can you please add the ability to run `kubectl edit workspace` and allow me to edit any of the properties within `workspace.inference.adapters.source`?

**Describe alternatives you've considered**

Alternative is to do a `kubectl replace -f somemanifest.yaml` which may take a while to delete and reprovision the GPU node. 

**Additional context**

In deploying a workspace, I made a user-error in mistyping my ACR repository URL and did not find the error until I noticed the RESOURCEREADY was "True", but INFERENCEREADY never became "True" after several minutes of waiting. That's when I attempted a `kubectl edit workspace` command but encountered an error stating that the workspace field is not editable.

**Comment by ishaansehgal99** [comment]
Release v0.3.1 added this feature!
